version: '3.4'

networks:
  fitness-microservice-network:
    name: fitness_network  

services:
  mssql:
    build:
      context: .
      dockerfile: sql.Dockerfile
    container_name: fitnessmicroservices.mssql
    restart: always
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "a?i0/cEFB@v3dweF7C"
    user: root
    ports: 
      - "1440:1433"
    #volumes: 
    #  - "identitysqldata:/var/opt/mssql"
    networks:
        - fitness-microservice-network
    
  seq:
    image: datalust/seq
    restart: unless-stopped 
    ports:
        - 5341:80
    environment:
         - ACCEPT_EULA=Y
    networks:
        - fitness-microservice-network

volumes:
  identitysqldata: